# Generated by Django 2.1.2 on 2019-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperPhrase', models.TextField()),
                ('welcomePhrase', models.TextField()),
                ('lowerPhrase', models.TextField()),
            ],
            options={
                'verbose_name': 'Welcome',
                'verbose_name_plural': 'Welcome',
            },
        ),
    ]
