# Generated by Django 2.1.2 on 2019-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_image', models.ImageField(upload_to='')),
                ('sample_name', models.CharField(max_length=150)),
                ('sample_description', models.TextField()),
            ],
            options={
                'verbose_name': 'HallCategories',
                'verbose_name_plural': 'HallCategories',
            },
        ),
        migrations.CreateModel(
            name='HallCategoryPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_categories_phrase', models.TextField()),
            ],
            options={
                'verbose_name': 'CategoryPhrase',
            },
        ),
    ]
