# Generated by Django 2.1.2 on 2019-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumbi', '0002_hallcategory_hallcategoryphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_image', models.ImageField(upload_to='')),
                ('latest_name', models.CharField(max_length=150)),
                ('latest_description', models.TextField()),
            ],
            options={
                'verbose_name': 'latest',
            },
        ),
        migrations.CreateModel(
            name='LatestPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_phrase', models.TextField()),
            ],
            options={
                'verbose_name': 'latest phrase',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_image', models.ImageField(upload_to='')),
                ('recommendation_name', models.CharField(max_length=150)),
                ('recommendation_description', models.TextField()),
            ],
            options={
                'verbose_name': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='RecommendedPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_phrase', models.TextField()),
            ],
            options={
                'verbose_name': 'recommendation phrase',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150)),
                ('service_description', models.TextField()),
            ],
            options={
                'verbose_name': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServicePhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_phrase', models.TextField()),
            ],
            options={
                'verbose_name': 'service Phrase',
            },
        ),
    ]
